# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: true
    steps:
    - script: echo "hi there :)"
- stage: dev_deploy
  jobs: 
  - deployment: dev_deploy
    pool: 
      vmImage: 'ubuntu-latest'
    environment: 'dev-hello'
    strategy: 
     runOnce:
       deploy:
         steps:
         - script: echo "hello dev world !!"
         - script: echo "filetemplate:$(System.DefaultWorkingDirectory)/arm/template.json"
         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
             deploymentScope: 'Resource Group'
             azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(d860292c-5d2c-4df3-b7c8-332bd46882d1)'
             subscriptionId: 'd860292c-5d2c-4df3-b7c8-332bd46882d1'
             action: 'Create Or Update Resource Group'
             resourceGroupName: 'user-service'
             location: 'West Europe'
             templateLocation: 'Linked artifact'
             csmFile: '$(System.DefaultWorkingDirectory)/arm/template.json'
             csmParametersFile: '$(System.DefaultWorkingDirectory)/arm/params.dev.json'
             deploymentMode: 'Incremental'