# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo "hi there :)"
- stage: dev_deploy
  jobs: 
  - deployment: dev_deploy
    pool: 
      vmImage: 'Ubuntu-16-04'
    environment: 'dev-hello'
    strategy: 
     runOnce:
       deploy:
         steps:
         - script: echo "hello dev world !!"