# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: false
    steps:
    - script: echo "Build tasks"
    - checkout: self
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: FunctionApp
- stage: dev_deploy
  jobs: 
  - deployment: dev_deploy
    pool: 
      vmImage: 'ubuntu-latest'
    environment: 'user-service-dev'
    strategy: 
     runOnce:
       deploy:
         steps:
         - checkout: self
         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
             deploymentScope: 'Resource Group'
             azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(d860292c-5d2c-4df3-b7c8-332bd46882d1)'
             subscriptionId: 'd860292c-5d2c-4df3-b7c8-332bd46882d1'
             action: 'Create Or Update Resource Group'
             resourceGroupName: 'user-service-dev'
             location: 'West Europe'
             templateLocation: 'Linked artifact'
             csmFile: '$(System.DefaultWorkingDirectory)/arm/template.bicep'
             csmParametersFile: '$(System.DefaultWorkingDirectory)/arm/params.dev.json'
             deploymentMode: 'Incremental'
         - download: current
           artifact: FunctionApp
         - task: AzureFunctionApp@1
           inputs:
             azureSubscription: 'Visual Studio Enterprise Subscription(d860292c-5d2c-4df3-b7c8-332bd46882d1)'
             appType: 'functionApp'
             appName: 'site-myApp-user-service-dev-westeurope'
             package: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
             deploymentMethod: 'auto'             
- stage: tst_deploy
  jobs: 
  - deployment: tst_deploy
    pool: 
      vmImage: 'ubuntu-latest'
    environment: 'user-service-tst'
    strategy: 
     runOnce:
       deploy:
         steps:
         - checkout: self
         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
             deploymentScope: 'Resource Group'
             azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(d860292c-5d2c-4df3-b7c8-332bd46882d1)'
             subscriptionId: 'd860292c-5d2c-4df3-b7c8-332bd46882d1'
             action: 'Create Or Update Resource Group'
             resourceGroupName: 'user-service-tst'
             location: 'West Europe'
             templateLocation: 'Linked artifact'
             csmFile: '$(System.DefaultWorkingDirectory)/arm/template.bicep'
             csmParametersFile: '$(System.DefaultWorkingDirectory)/arm/params.tst.json'
             deploymentMode: 'Incremental'
         - download: current
           artifact: FunctionApp             
         - task: AzureFunctionApp@1
           inputs:
             azureSubscription: 'Visual Studio Enterprise Subscription(d860292c-5d2c-4df3-b7c8-332bd46882d1)'
             appType: 'functionApp'
             appName: 'site-myApp-user-service-dev-westeurope'
             package: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
             deploymentMethod: 'auto'
- stage: prd_deploy
  jobs: 
  - deployment: prd_deploy
    pool: 
      vmImage: 'ubuntu-latest'
    environment: 'user-service-prd'
    strategy: 
     runOnce:
       deploy:
         steps:
         - checkout: self
         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
             deploymentScope: 'Resource Group'
             azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(d860292c-5d2c-4df3-b7c8-332bd46882d1)'
             subscriptionId: 'd860292c-5d2c-4df3-b7c8-332bd46882d1'
             action: 'Create Or Update Resource Group'
             resourceGroupName: 'user-service-prd'
             location: 'West Europe'
             templateLocation: 'Linked artifact'
             csmFile: '$(System.DefaultWorkingDirectory)/arm/template.bicep'
             csmParametersFile: '$(System.DefaultWorkingDirectory)/arm/params.prd.json'
             deploymentMode: 'Incremental'
         - download: current
           artifact: FunctionApp             
         - task: AzureFunctionApp@1
           inputs:
             azureSubscription: 'Visual Studio Enterprise Subscription(d860292c-5d2c-4df3-b7c8-332bd46882d1)'
             appType: 'functionApp'
             appName: 'site-myApp-user-service-prd-westeurope'
             package: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
             deploymentMethod: 'auto'             